spring:
  application:
    name: fleur-atelier-api
  datasource:
    url: jdbc:h2:mem:fleur_atelier_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8080

security:
  jwt:
    secret: ${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
    expiration-ms: 3600000


# !!!! IMPORTANT: My JWT_SECRET above is a default value for development purposes only.
